name: .NET Core

on:
  push:
    branches: [ containarized_aks_allup ]
  pull_request:
    branches: [ containarized_aks_allup ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      imageRepository: 'globoticket.web'
      containerRegistry: 'globoticket.azurecr.io'
      dockerfilePath: 'GloboTicket/GloboTicket.Client/Dockerfile'
      deploymentFile: 'aks-globoticket.web.yaml'
      trivyVersion: 0.12.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{env.containerRegistry}}/${{env.imageRepository}}:${{GITHUB_RUN_ID}}
        file: ${{env.dockerfilePath}}
        context: ${{GITHUB_WORKSPACE}}/GloboTicket
