name: globoticket.web

on:
  push:
    branches: [ containarized_aks_allup ]
    paths:
    - '.github/workflows/globoticket.web.yaml'
    - 'GloboTicket/GloboTicket.Client/**'
    - 'GloboTicket/aks-globoticket.web.yaml'
  pull_request:
    branches: [ containarized_aks_allup ]
    paths:
    - '.github/workflows/globoticket.web.yaml'
    - 'GloboTicket/GloboTicket.Client/**'
    - 'GloboTicket/aks-globoticket.web.yaml'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      imageRepository: 'globoticket.web'
      containerRegistry: 'globoticketacr.azurecr.io'
      dockerfilePath: 'GloboTicket/GloboTicket.Client/Dockerfile'
      deploymentFile: 'aks-globoticket.web.yaml'
      trivyVersion: 0.12.0
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.containerRegistry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}} -f ${{env.dockerfilePath}} ${{github.workspace}}/GloboTicket
  
    - name: install trivy scanning
      run: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v${{env.trivyVersion}}/trivy_${{env.trivyVersion}}_Linux-64bit.deb
        sudo dpkg -i trivy_${{env.trivyVersion}}_Linux-64bit.deb
        trivy -v

    - name: Run container scanner for known vulnerabilities
      run: |
            trivy image --exit-code 0 --severity LOW,MEDIUM  ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
            trivy image --exit-code 1 --severity HIGH,CRITICAL ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}

    - name: Push image to ACR
      run: |
        docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
    
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: ${{github.workspace}}/GloboTicket/${{env.deploymentFile}}
      env: 
        Build.BuildId: ${{github.run_number}}
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}} 
      id: setcontext
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            ${{github.workspace}}/GloboTicket/${{env.deploymentFile}}
